### ISSUE TITLE
AMTEL1284 Firmware

### ISSUE THREAD

**Issue by SwitchGB** [InsaneDruid/CBM-D9096#1]
I cant see the firmware for the AMTEL1284 in the git download.

**Comment by InsaneDruid** [comment]
That's because it uses the official firmware of the petsd+ (the sd2iec bootloader and the nodiskemu firmware). So its the same as in any other PetSD+ implementation.

A good explanation is found here: http://www.primrosebank.net/computers/pet/projects/pet_petsd_fw.htm

Basically, you flash the *New Bootloader for 16Mhz petSD+* (found in the link above) to the ATMEL. Set the Fuses to

### Fuse Low Byte: F7
CKSEL3=0

### Fuse High Byte: D2
SPIEN
EESAVE=0
BOOTSZ1=0
BOOTRST=0

### Extended Fuse Byte: FC
BODLEVEL1=0
BODLEVEL0=0

Then get the NODISKEMU firmware (i recommend the 2017-10-05 release as it hasn't the cold boot bug and all the features needed) from https://petsd.net/nightlies.php, put the file on a SD card (needs to be named "petSD+.bin") and during the first boot the bootloader will flash the firmware.

**Comment by SwitchGB** [comment]
That helped a lot, I seem to now have firmware loading, at least there is a lot of flashing of the activity light while the error light is on then it all stops and on the next boot just a couple of flashes. I cant yet get anything from the drive but will test my IEEE488 port next.

**Comment by InsaneDruid** [comment]
I added a readme section about SD card interface board compatibility. I had massive issues with a board that just used resistors and a voltage regulator for the card itself (ARD MODULE SD Arduino - SD-Karten-Modul from reichelt.de).
*DEBO MICROSD 2* and *C-Control Pro Nr. 197220* (Micro SD and standard SD size) are tested to be fully working. Both use real level shifters to interface all the signals and are as cheap as the ones using passives.

**Comment by SwitchGB** [comment]
Ok some progress I am sure the firmware is loading ok, from a fresh bootloader with no SDCard a 'directory' command  returns '?device not present error'
Once the SD Card is installed and the bootloader has finished installing the firmware and rebooted the 'directory' command  returns 'ready'

However I can not get a directory listing or see any programs copied to the SD Card.

loading returns '?file not found error'

So I was wondering about SD Card compatibility but thinking that the firmware has loaded ok makes me think the application is reading the card ok ?

I have a Kingston 32GB MicroSD Class 10 Card (795545125553) formatted to FAT32.

Any Ideas ?

Here is a picture of my progress so far :)
![IMG_1067](https://github.com/user-attachments/assets/08d2c495-abb6-48c7-95b8-6cd27f8c2cb7)

**Comment by InsaneDruid** [comment]
CD and WP (disk change and write protect) need to be either connected to a card interface that support them or need to be grounded. Thats what J3 (both pins are GND) is for: if you install pin headers to J3 and the 2 last pins pf J2 you can put on some jumpers - or just use solder to bridge over.

**Comment by SwitchGB** [comment]
Yes I have them grounded see here:
![IMG_1071](https://github.com/user-attachments/assets/ea873668-aec5-41d1-b4b3-889fbba8825b)

**Comment by SwitchGB** [comment]
Do you have a list of MicroSD Cards that are known working ?

**Comment by InsaneDruid** [comment]
SanDisk Ultra microSDHC do work, and some no names, too.

Have you tried device numbers other then 8? 
like catalog onu 9/10/11/12?

you can change the device number laterwith the U0 command
https://github.com/nils-eilers/NODISKEMU?tab=readme-ov-file#u0

and then save the config with the XW command.

For 3 LED you should remove R6 btw, and what value are R5 and R6? Really 6.5 Ohms? (blue green black silver brown)?

**Comment by SwitchGB** [comment]
Whoop :) it works :)

it was the device number - cAu11 worked and retuned a listing and I can run a program.
Its on U11 - Not sure why its defaulted to that need to investigate.

Yes the resistors are correct, probably the light they came in a kit on Amazon 1% but you are right they multiplier looks more silver than gold.

<img width="267" alt="Screenshot 2024-07-24 at 07 54 51" src="https://github.com/user-attachments/assets/17252c84-e63c-4c7d-9d60-96307fdbd3df">

**Comment by InsaneDruid** [comment]
Nice!

As said, if you want to change the id, the U0> command is the way to go

OPEN1,11,15,"U0>"+chr$(new address):CLOSE1
And then save the config with
OPEN1,11,15,"XW":CLOSE1

I also highly recommend setting the extension hiding to be enabled
OPEN1,11,15,"XE+":CLOSE1

Then you can leave the .prg or .d64 etc. extensions on the file names. Makes it easier on the PC side imho.

**Comment by SwitchGB** [comment]
Excellent now working as expected on 8  :) I must thank you for your help would have induced a lot more frustration if I worked it out on my own :)

So the ONLY issue I now have is it takes 3-4 reboots from cold before the activity light goes off and the board functions, have you came across this - I have not tried later firmware only the one you recommended :)

**Comment by InsaneDruid** [comment]
This is a known problem of all PetSD+, but actually one that happens on the firmware builds AFTER the 2017-10-05 build: http://www.primrosebank.net/computers/pet/projects/pet_petsd_fw_revs.htm

Unfortunately, the dev abandoned the firmware and the issue never really was found, or fixed.

What I found though is that is better to switch the low voltage supply and not the power to a PSU powering the board.  (the board needs clean and stable power right from the beginning)
